---
- name: Download Java
  command: "wget -q -O {{java_archive}} --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' {{download_url}} creates={{java_archive}}"
- name: UnTar, Unzip
  unarchive: 
    src: "{{ java_archive }}"
    dest: "{{ apps_folder }}"
    copy: no
- name: symbolic link
  file:
    src: "{{ java_name }}"
    dest: "{{ java_symbolic_link }}"
    state: link